### ISSUE TITLE
Calling createInspector breaks the dom

### ISSUE THREAD

**Issue by dimensi** [sergeysova/effector-logger#4]
If you remove the effector -> effector-logger substitution and leave createInspector, it breaks the house at the first update of any of the strings of the effector.
Example: https://tic-tac-toe-2gk598mdc.now.sh/ (look in devtools)
Code https://github.com/dimensi/tic-tac-toe/tree/5bc0eb9d2cbd97f685b4e70cf5002a4b9c361c25

**Comment by sergeysova** [comment]
@dimensi Please, update to https://github.com/sergeysova/effector-logger/releases/tag/v0.3.0
